### ISSUE TITLE
Make statusbar font color white

### ISSUE THREAD

**Issue by Laumania** [awolf/Xamarin-Forms-InAnger#3]
It's a minor thing, I just really hate when the background is dark and the statusbar color is black.

Would it be ok if I changed it to white?
It's also great to people to see how that is done.

**Comment by awolf** [comment]
Sure, I can see that. Please send a pull request.

**Comment by Laumania** [comment]
Ok I'll send one later :)



Den 17/04/2015 kl. 21.24 skrev Adam <notifications@github.com>:

Sure, I can see that. Please send a pull request.

—
Reply to this email directly or view it on GitHub
<https://github.com/awolf/Xamarin-Forms-InAnger/issues/3#issuecomment-94057410>
.

**Comment by awolf** [comment]
Thank you for the pull request.
