### ISSUE TITLE
Unable to build on Indie license due to profiling

### ISSUE THREAD

**Issue by Laumania** [awolf/Xamarin-Forms-InAnger#6]
The currently latest version https://github.com/awolf/Xamarin-Forms-InAnger/commit/85bc4c07b977927690df50160e269b0d6e091fae
doesn't build on my machine, apparently due to my Indie license not being good enough for the compiler flags :P

![screen shot 2015-06-04 at 15 14 29](https://cloud.githubusercontent.com/assets/1378458/7984884/a3a1f91c-0acc-11e5-8391-7354404cc687.png)

**Comment by awolf** [comment]
I'll have to switch that off and commit the new version. Can you just turn off that option and try to compile?

**Comment by Laumania** [comment]
Yep, works. :)

**Comment by awolf** [comment]
I have removed the profiling from the iOS project.
